package atividade103.telas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import atividade103.model.Filme;
import atividade103.model.FilmeDAO;

/**
 *
 * @author tiluc
 */
public class FilmeListagem extends javax.swing.JFrame {

    public FilmeListagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaDeBoasVindas = new javax.swing.JPanel();
        TextoDeBoasVindas = new javax.swing.JLabel();
        TextoDeFeedback = new javax.swing.JLabel();
        BotaoSair = new javax.swing.JButton();
        AreaDaTabela = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PesquisaTextField = new javax.swing.JTextField();
        BuscarjButton = new javax.swing.JButton();
        ScrollDaTabela = new javax.swing.JScrollPane();
        TabelaDeFilme = new javax.swing.JTable();
        BotaoNovoFilme = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();
        BotaoAssistir = new javax.swing.JButton();
        BotaoAssistir1 = new javax.swing.JButton();
        BotaoExcluir1 = new javax.swing.JButton();
        BotaoNovoFilme1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        AreaDeBoasVindas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AreaDeBoasVindasKeyPressed(evt);
            }
        });

        TextoDeBoasVindas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextoDeBoasVindas.setText("Lista de Filmes");

        TextoDeFeedback.setText("Abaixo, estão todos os filmes cadastrados:");

        BotaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atividade103/icones/sair.png"))); // NOI18N
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AreaDeBoasVindasLayout = new javax.swing.GroupLayout(AreaDeBoasVindas);
        AreaDeBoasVindas.setLayout(AreaDeBoasVindasLayout);
        AreaDeBoasVindasLayout.setHorizontalGroup(
            AreaDeBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaDeBoasVindasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AreaDeBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AreaDeBoasVindasLayout.createSequentialGroup()
                        .addComponent(TextoDeFeedback)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AreaDeBoasVindasLayout.createSequentialGroup()
                        .addComponent(TextoDeBoasVindas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoSair)))
                .addContainerGap())
        );
        AreaDeBoasVindasLayout.setVerticalGroup(
            AreaDeBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaDeBoasVindasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AreaDeBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoDeBoasVindas)
                    .addComponent(BotaoSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextoDeFeedback)
                .addContainerGap())
        );

        jLabel1.setText("Pesquisar por nome:");

        PesquisaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisaTextFieldActionPerformed(evt);
            }
        });

        BuscarjButton.setText("Buscar");
        BuscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarjButtonActionPerformed(evt);
            }
        });

        TabelaDeFilme.setModel(montarTabela(FilmeDAO.listarTodos()));
        ScrollDaTabela.setViewportView(TabelaDeFilme);

        BotaoNovoFilme.setText("+ Novo Filme");
        BotaoNovoFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoFilmeActionPerformed(evt);
            }
        });

        BotaoExcluir.setText("Excluir");
        BotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirActionPerformed(evt);
            }
        });

        BotaoAssistir.setText("Assistir");
        BotaoAssistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAssistirActionPerformed(evt);
            }
        });

        BotaoAssistir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atividade103/icones/ver.png"))); // NOI18N
        BotaoAssistir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAssistir1ActionPerformed(evt);
            }
        });

        BotaoExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atividade103/icones/delete.png"))); // NOI18N
        BotaoExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluir1ActionPerformed(evt);
            }
        });

        BotaoNovoFilme1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atividade103/icones/new.png"))); // NOI18N
        BotaoNovoFilme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoFilme1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AreaDaTabelaLayout = new javax.swing.GroupLayout(AreaDaTabela);
        AreaDaTabela.setLayout(AreaDaTabelaLayout);
        AreaDaTabelaLayout.setHorizontalGroup(
            AreaDaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollDaTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(AreaDaTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PesquisaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuscarjButton))
            .addGroup(AreaDaTabelaLayout.createSequentialGroup()
                .addGroup(AreaDaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BotaoNovoFilme)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AreaDaTabelaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(BotaoNovoFilme1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(AreaDaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BotaoExcluir)
                    .addComponent(BotaoExcluir1))
                .addGap(18, 18, 18)
                .addGroup(AreaDaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoAssistir1)
                    .addComponent(BotaoAssistir)))
        );
        AreaDaTabelaLayout.setVerticalGroup(
            AreaDaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaDaTabelaLayout.createSequentialGroup()
                .addGroup(AreaDaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(PesquisaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarjButton))
                .addGap(9, 9, 9)
                .addComponent(ScrollDaTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AreaDaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoNovoFilme)
                    .addComponent(BotaoExcluir)
                    .addComponent(BotaoAssistir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AreaDaTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoNovoFilme1)
                    .addComponent(BotaoExcluir1)
                    .addComponent(BotaoAssistir1))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem1.setText("Atualizar a lista de filmes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AreaDeBoasVindas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AreaDaTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AreaDeBoasVindas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AreaDaTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotaoSairActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        TabelaDeFilme.setModel(montarTabela(FilmeDAO.listarTodos()));
        ScrollDaTabela.setViewportView(TabelaDeFilme);
    }//GEN-LAST:event_formWindowGainedFocus

    private void BotaoNovoFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoNovoFilmeActionPerformed

    private void BotaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoExcluirActionPerformed

    private void BotaoAssistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAssistirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoAssistirActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Tecla foi pressionada.");
        if(evt.getKeyCode() == evt.VK_F5) {
            
        }
    }//GEN-LAST:event_formKeyPressed

    private void AreaDeBoasVindasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AreaDeBoasVindasKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AreaDeBoasVindasKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TabelaDeFilme.setModel(montarTabela(FilmeDAO.listarTodos()));
        ScrollDaTabela.setViewportView(TabelaDeFilme);
        JOptionPane.showMessageDialog(null, "Lista atualizada com sucesso!");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BuscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarjButtonActionPerformed
        // TODO add your handling code here:
        List<Filme> lista = FilmeDAO.filtrarPorNome(PesquisaTextField.getText());
        TabelaDeFilme.setModel(montarTabela(lista));
        ScrollDaTabela.setViewportView(TabelaDeFilme);
    }//GEN-LAST:event_BuscarjButtonActionPerformed

    private void PesquisaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesquisaTextFieldActionPerformed

    private void BotaoAssistir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAssistir1ActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = getPosicao();
        FilmeVisto tela = new FilmeVisto(linhaSelecionada);
        tela.setVisible(true);        
    }//GEN-LAST:event_BotaoAssistir1ActionPerformed

    private void BotaoExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluir1ActionPerformed
        // TODO add your handling code here:
        int id = getPosicao();
        
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse registro?");
        if (resposta == 0) {
          FilmeDAO.excluir(id);
        } 
        
        TabelaDeFilme.setModel(montarTabela(FilmeDAO.listarTodos()));
        ScrollDaTabela.setViewportView(TabelaDeFilme);        
    }//GEN-LAST:event_BotaoExcluir1ActionPerformed

    private void BotaoNovoFilme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoFilme1ActionPerformed
        // TODO add your handling code here:
        FilmeCadastro tela = new FilmeCadastro();
        tela.setVisible(true);        
    }//GEN-LAST:event_BotaoNovoFilme1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmeListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmeListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmeListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmeListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmeListagem().setVisible(true);
            }
        });
    }

    private DefaultTableModel montarTabela(List<Filme> lista) {
        String[] colunas = {"ID", "Nome", "Data de lançamento", "Categoria", "Assistido"};
        
        // Criamos a tabela
        DefaultTableModel tabela = new DefaultTableModel(colunas, 0);
       
        //ArrayList<Filme> lista = ListaFilme.Listar();
        
        for (int i=0; i < lista.size(); i++) {
            Filme p = lista.get(i);
            
            String assistido = "";
            if (p.isAssistido()) {
                assistido = "Sim";
            } else {
                assistido = "Não";
            }
            
            String[] linha = {
                Integer.toString(p.getId()),
                p.getNome(),
                Filme.converterParaJava(p.getDataLancamento()),
                p.getCategoria(),
                assistido,
            };
            
            tabela.addRow(linha);
        }
        
        return tabela;
    }
        
    private int getPosicao() {
        int posicao = TabelaDeFilme.getSelectedRow();
        
        if(posicao <= -1) {
            JOptionPane.showMessageDialog(null, "Selecione um item para excluir.");
        }
                
        return Integer.parseInt( (String) TabelaDeFilme.getValueAt(posicao, 0) );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AreaDaTabela;
    private javax.swing.JPanel AreaDeBoasVindas;
    private javax.swing.JButton BotaoAssistir;
    private javax.swing.JButton BotaoAssistir1;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoExcluir1;
    private javax.swing.JButton BotaoNovoFilme;
    private javax.swing.JButton BotaoNovoFilme1;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JButton BuscarjButton;
    private javax.swing.JTextField PesquisaTextField;
    private javax.swing.JScrollPane ScrollDaTabela;
    private javax.swing.JTable TabelaDeFilme;
    private javax.swing.JLabel TextoDeBoasVindas;
    private javax.swing.JLabel TextoDeFeedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}